mysql

diff --git a/mysqlinstall b/mysqlinstall
--- a/mysqlinstall
+++ b/mysqlinstall
@@ -1,12 +1,35 @@
 #!/bin/bash
 
-dnf install mysql -y
+user=$( id -u )
 
-if [ $? -eq 0 ]
+if [ $user -eq 0 ]
 then 
     echo "You are running in root access"
 else
     echo "you don't have root access to install mysql"
+    exit 1
 
 fi
+
+dnf install mysql -y
+
+if [ $? -eq 0 ]
+then 
+    echo "You already have mysql installed"
+else
+    echo "You need to install mysql"
+    exit 1
+fi
+
+dnf list installed mysql
+
+if [ $? -eq 0 ]
+then 
+    echo "Your mysql installation is Success"
+else
+    echo "Your mysql installation Failed"
+
+fi
+
+
 
