mysql

diff --git a/mysqlinstall b/mysqlinstall
--- a/mysqlinstall
+++ b/mysqlinstall
@@ -2,12 +2,13 @@
 
 USERID=$(id -u)
 
-if [ $USERID -ne 0 ] 
+if [ $USERID -eq 0 ] 
 then
-    echo "ERROR:: Please run this script in root access"
-    #exit 1 #gives status code other than 0
-else
     echo "You are running in root access"
+     #gives status code other than 0
+else
+    echo "ERROR:: Please run this script in root access"
+    exit 1
 fi
 
 dnf install mysqldfff -y
